"""Message kind and tag

Revision ID: 1326e6b76924
Revises: 9dc336a9af64

For context compaction (0.23.0). ``kind`` is ``message`` for every existing row, or
``compaction`` for a compaction row; ``tag`` is ``tool:<name>`` on tool results or what
an app set. The index serves ``list_for_model``'s lookup of the latest compaction row.
Existing rows keep ``kind='message'`` and a NULL tag.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1326e6b76924"
down_revision: str | None = "9dc336a9af64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "actant_messages",
        sa.Column("kind", sa.Text(), server_default=sa.text("'message'"), nullable=False),
    )
    op.add_column("actant_messages", sa.Column("tag", sa.Text(), nullable=True))
    op.create_index(
        "ix_actant_messages_thread_kind",
        "actant_messages",
        ["agent_id", "thread_id", "kind", "created_at", "message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_actant_messages_thread_kind", table_name="actant_messages")
    op.drop_column("actant_messages", "tag")
    op.drop_column("actant_messages", "kind")
    # ### end Alembic commands ###
