"""Context compaction

Revision ID: aedae3e341f4
Revises: 9dc336a9af64

Two new tables for model-context compaction (0.23.0); no existing table changes.
``actant_compactions`` holds one row per compaction of a thread's model context: the
boundary in the transcript and the summary. ``actant_pinned_notes`` holds a thread's
durable notes, re-injected verbatim after every summary.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "aedae3e341f4"
down_revision: str | None = "9dc336a9af64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actant_compactions",
        sa.Column("compaction_id", sa.Text(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("turn_id", sa.Text(), nullable=False),
        sa.Column("boundary", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("pinned_blocks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tokens_before", sa.Integer(), nullable=False),
        sa.Column("images_before", sa.Integer(), nullable=False),
        sa.Column("tokens_after", sa.Integer(), nullable=False),
        sa.Column("images_after", sa.Integer(), nullable=False),
        sa.Column("context_window_tokens", sa.Integer(), nullable=True),
        sa.Column("max_images_per_request", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("compaction_id"),
    )
    op.create_index(
        "ix_actant_compactions_thread",
        "actant_compactions",
        ["agent_id", "thread_id", "boundary"],
        unique=False,
    )
    op.create_table(
        "actant_pinned_notes",
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("content_blocks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("agent_id", "thread_id", "key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("actant_pinned_notes")
    op.drop_index("ix_actant_compactions_thread", table_name="actant_compactions")
    op.drop_table("actant_compactions")
    # ### end Alembic commands ###
